measurements = open("measurements.txt", "r")
measure1 = float(measurements.readline())
measure2 = float(measurements.readline())
measure3 = float(measurements.readline())
measure4 = float(measurements.readline())
measure5 = float(measurements.readline())
expected = float(measurements.readline())
mu = round((measure1 + measure2 + measure3 + measure4 + measure5)/ 5, 2)
stdDev = round((((measure1 - mu)**2 + (measure2 - mu)**2 + (measure3 - mu)**2 + (measure4 - mu)**2 + (measure5 - mu)**2)/5)**0.5, 2)
t = round((mu - expected)/stdDev, 2)
avg = round(mu, 2)
str_avg = str(avg)
str_t = str(t)
str_dev = str(stdDev)
fileOpen = open("conclusions.txt", "w")
fileOpen.write("Lab results:\n average = " + str_avg + "\n sigma = " + str_dev + "\n t-score = " + str_t)